title: Ajay's Dev Hub
description: Systems, Networking, DPDK, VPP, OS & System Design learning hub
url: "https://ajay3007.github.io"
baseurl: "/ajdevhub"

markdown: kramdown
theme: null

plugins:
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - ../src
  - node_modules
  - tools
  - README.md
  - _site
